language: cpp

sudo: required
dist: xenial
services:
        - xvfb

branches:
    only:
        - master
        - development
        - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

matrix:
    include:
        - os: linux
          env: COMPILER=g++-5.4 CMAKE_BUILD_TYPE=Debug

        - os: osx
          env: COMPILER=clang++ CMAKE_BUILD_TYPE=Debug

install:
    - |
      if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        export DISPLAY=:99.0 &&
        sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test &&
        sudo apt-get install p7zip-full &&
        if [ "${COMPILER}" = "g++-5.4" ]; then
          export CXX="g++" &&
          export CC="gcc"
        elif [ "${COMPILER}" = "clang++" ]; then
          export CXX="clang++" &&
          export CC="clang"
        fi
      else
        brew update &&
        brew unlink cmake &&
        brew install cmake &&
        brew link cmake &&
        brew install p7zip
      fi

script:
    - |
      export DIR=$(pwd) &&
      mkdir build &&
      cd build &&
      cmake -DCMAKE_INSTALL_PREFIX=$(pwd)/installdir .. &&
      make &&
      make install &&
      if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        export OSNAME="linux"
      else
        export OSNAME="mac"
      fi
      export PLATFORM=$(uname -p) &&
      export DEPLOYMENT_TARGET=ciuploadtool-testing_${OSNAME}_${PLATFORM}_${TRAVIS_COMMIT:0:7}.zip &&
      cd installdir/bin &&
      7z a $DEPLOYMENT_TARGET * &&
      cd ../../

after_success:
    - |
      if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        wget https://github.com/d1vanov/ciuploadtool/releases/download/continuous-development/ciuploadtool_linux.zip &&
        unzip ciuploadtool_linux.zip
      else
        wget https://github.com/d1vanov/ciuploadtool/releases/download/continuous-development/ciuploadtool_mac.zip &&
        unzip ciuploadtool_mac.zip
      fi
    - chmod 755 ciuploadtool
    - ./ciuploadtool -verbose -suffix="$TRAVIS_BRANCH" installdir/bin/$DEPLOYMENT_TARGET
