version: '0.4.1-{build}'

image:
  - Visual Studio 2017
  - Ubuntu2004

branches:
  only:
    - master
    - development
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

environment:
  auth_token:
    secure: 7PAadWhv0Xoxt7rz4NeSWaaSVEtPW0R01ZlHJ7Rqn8QEVKs4i0aBcjWtn7JiN7+X
  matrix:
    - prepare_mode: YES
      name: win32
      platform: amd64_x86
    - prepare_mode: NO
      name: win32
      platform: amd64_x86

clone_folder: c:\dev\ciuploadtool-testing

init:
  - set ORIGPATH=%PATH%
  - set tool=VS2017_x86
  - set DEPLOYMENT_TARGET=ciuploadtool-testing_windows-%tool%_%APPVEYOR_REPO_COMMIT:~0,7%.zip
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x86
  - set PATH="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin";%PATH%

install:
  - md c:\dev\ciuploadtool
  - cd c:\dev\ciuploadtool
  - curl -fsSL https://github.com/d1vanov/ciuploadtool/releases/download/continuous-development/ciuploadtool_windows_x86.zip -o ciuploadtool_windows_x86.zip
  - 7z x ciuploadtool_windows_x86.zip

before_build:
  - cd c:\dev\ciuploadtool-testing
  - md build

build_script:
  - if %prepare_mode%==YES c:\dev\ciuploadtool\ciuploadtool.exe -suffix="%APPVEYOR_REPO_BRANCH%" -preponly
  - ps: if ($env:prepare_mode -eq "YES") { throw "Failing in order to stop the current build matrix job early" }
  - cd c:\dev\ciuploadtool-testing\build
  - cmake .. -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX="c:/dev/install"
  - cmake --build . --target all
  - cmake --build . --target install

after_build:
  - cd c:\dev
  - 7z a %DEPLOYMENT_TARGET% c:\dev\install\*
  - md %APPVEYOR_BUILD_FOLDER%\artifacts
  - cp %DEPLOYMENT_TARGET% %APPVEYOR_BUILD_FOLDER%\artifacts

artifacts:
  - path: 'artifacts\*.zip'
    name: archive

on_finish:
  - set PATH=C:\go\bin;%PATH%
  - echo "APPVEYOR_REPO_BRANCH = "
  - echo %APPVEYOR_REPO_BRANCH%
  - cd c:\dev
  - c:\dev\ciuploadtool\ciuploadtool.exe -verbose -suffix="%APPVEYOR_REPO_BRANCH%" %APPVEYOR_BUILD_FOLDER%\artifacts\*

matrix:
  fast_finish: true
  allow_failures:
    - prepare_mode: YES
