version: '0.4.1-{build}'

image:
  - Visual Studio 2017
#  - Ubuntu2004

branches:
  only:
    - master
    - development
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

environment:
  auth_token:
    secure: 7PAadWhv0Xoxt7rz4NeSWaaSVEtPW0R01ZlHJ7Rqn8QEVKs4i0aBcjWtn7JiN7+X
  matrix:
    - prepare_mode: YES
      name: win32
      platform: amd64_x86
    - prepare_mode: NO
      name: win32
      platform: amd64_x86

clone_folder:
  - c:\dev\ciuploadtool-testing

init:
  - ps: ./init.ps1

install:
  - ps: ./install.ps1

before_build:
  - ps: ./before_build.ps1

build_script:
  - ps: ./build_script.ps1

after_build:
  - ps: ./after_build.ps1

artifacts:
  - path: 'artifacts\*.zip'
    name: archive

on_finish:
  - ps: ./on_finish.ps1

matrix:
  fast_finish: true
  allow_failures:
    - prepare_mode: YES
