version: '0.1.0-{build}'

branches:
  only:
    - master
    - development
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

environment: 
  auth_token:
    secure: 7DjX/0v2lEQxR10o1vjqh5mrqgNB8rp1xANMofZYVDC5jzOiymdTQZqqbKFhXHyJ
  matrix:
    - prepare_mode: YES
      name: win32
      platform: x86
    - prepare_mode: NO
      name: win32
      platform: amd64_x86
    - prepare_mode: NO
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      name: win64
      platform: amd64
    - prepare_mode: NO
      name: win32
      platform: mingw

clone_folder: c:\dev\ciuploadtool-testing

init:
  - set ORIGPATH=%PATH%
  - if %platform%==amd64 set tool=VS2017_x64
  - if %platform%==amd64_x86 set tool=VS2015_x86
  - if %platform%==mingw set tool=MinGW_x86
  - set DEPLOYMENT_TARGET=ciuploadtool-testing_windows-%tool%_%APPVEYOR_REPO_COMMIT:~0,7%.zip
  - if %platform%==amd64 call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - if %platform%==amd64_x86 call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %platform%
  - if not %platform%==mingw (set makefiles="NMake Makefiles") else (set makefiles="MinGW Makefiles")
  - if %platform%==mingw set PATH=C:\MinGW\bin;C:\Program Files (x86)\CMake\bin;%PATH%
  - if %platform%==x64 set PATH="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin";%PATH%
  - if %platform%==x86 set PATH="C:\Program Files (x86)\MSBuild\14.0\Bin";%PATH%

install:
  - md c:\dev\ciuploadtool
  - cd c:\dev\ciuploadtool
  - curl -fsSL https://github.com/d1vanov/ciuploadtool/releases/download/continuous-master/ciuploadtool_windows_x86.zip -o ciuploadtool_windows_x86.zip
  - 7z x ciuploadtool_windows_x86.zip

before_build:
  - cd c:\dev\ciuploadtool-testing
  - md build

build_script:
  - if %prepare_mode%==YES c:\dev\ciuploadtool\ciuploadtool.exe -suffix="%APPVEYOR_REPO_BRANCH%" -preponly
  - ps: if ($env:prepare_mode -eq "YES") { throw "Failing in order to stop the current build matrix job early" }
  - cd c:\dev\ciuploadtool-testing\build
  - if %platform%==mingw set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - cmake .. -G %makefiles% -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX="c:/dev/install"
  - cmake --build . --target all
  - cmake --build . --target install
  - if %platform%==mingw set PATH=%ORIGPATH%

after_build:
  - cd c:\dev
  - 7z a %DEPLOYMENT_TARGET% c:\dev\install\*
  - md %APPVEYOR_BUILD_FOLDER%\artifacts
  - cp %DEPLOYMENT_TARGET% %APPVEYOR_BUILD_FOLDER%\artifacts

artifacts:
  - path: 'artifacts\*.zip'
    name: archive

on_finish:
  - set PATH=C:\go\bin;%PATH%
  - echo "APPVEYOR_REPO_BRANCH = "
  - echo %APPVEYOR_REPO_BRANCH%
  - cd c:\dev
  - c:\dev\ciuploadtool\ciuploadtool.exe -suffix="%APPVEYOR_REPO_BRANCH%" %APPVEYOR_BUILD_FOLDER%\artifacts\*

matrix:
  fast_finish: true
  allow_failures:
    - prepare_mode: YES
